"""
UI 自动化步骤关键字目录（与 frontend ActionGroup.js、Runner KeywordRegistry 对齐）
"""

UI_VALID_METHODS = {
    "open_browser", "open_url", "refresh", "go_back", "scroll_to_height", "execute_script",
    "save_page_img", "open_new_page", "switch_to_page", "close_page",
    "reset_browser_context", "close",
    "fill_value", "click_ele", "double_click_ele", "clear_value", "set_checked",
    "hover", "focus_element", "select_option", "type_value", "drag_and_drop",
    "long_click_element", "upload_file",
    "mouse_click", "move_mouse", "mouse_down", "mouse_up", "mouse_wheel",
    "press_key", "press_type",
    "frame_fill_value", "frame_click_element", "frame_hover", "frame_focus_element",
    "frame_select_option", "frame_type_value", "frame_long_click_element",
    "frame_drag_and_drop",
    "set_default_timeout", "wait_for_time", "wait_for_load", "wait_for_network",
    "wait_for_element",
    "wait_for_element_hidden", "wait_for_element_text_change", "wait_for_element_text_stable",
    "wait_for_clickable",
    "wait_for_url_contains", "wait_for_response", "wait_for_download",
    "accept_dialog", "dismiss_dialog",
    "scroll_to_element", "click_by_text", "click_if_exists", "fill_if_exists",
    "click_if_visible", "fill_if_visible", "switch_to_latest_page",
    "kw_assert_page_title", "kw_assert_page_url", "kw_assert_value",
    "kw_assert_element_text", "kw_assert_element_text_contains", "kw_assert_text_contains",
    "kw_assert_text_not_contains", "kw_assert_element_count", "kw_assert_text_length",
    "kw_assert_attribute", "kw_assert_attribute_exists", "kw_assert_attribute_not_exists",
    "kw_assert_visible",
    "kw_assert_hidden", "kw_assert_not_exist", "kw_assert_not_visible",
    "kw_assert_enabled", "kw_assert_disabled",
    "kw_assert_checked", "kw_assert_empty", "kw_assert_editable", "kw_assert_focused",
    "kw_db_assert",
    "extract_text", "extract_attribute", "extract_input_value", "extract_page_url",
    "extract_response_field",
    "smart_step",
    "smart_click", "smart_fill",
    "condition_branch",
    "click_by_image", "fill_by_image", "wait_for_image", "kw_assert_image", "kw_assert_image_not_exists",
}

# SMART-1：expected_after.type 白名单
SMART_EXPECTED_AFTER_TYPES = frozenset({
    "text_visible",
    "locator_visible",
    "locator_hidden",
    "url_contains",
    "value_equals",
})

UI_REQUIRED_PARAMS = {
    "open_url": {"url"},
    "fill_value": {"locator"},
    "click_ele": {"locator"},
    "double_click_ele": {"locator"},
    "clear_value": {"locator"},
    "set_checked": {"locator"},
    "hover": {"locator"},
    "focus_element": {"locator"},
    "select_option": {"locator", "value"},
    "type_value": {"locator"},
    "drag_and_drop": {"start_selector", "end_selector"},
    "long_click_element": {"locator"},
    "upload_file": {"locator"},
    "click_by_image": {"template"},
    "fill_by_image": {"template", "value"},
    "wait_for_image": {"template"},
    "kw_assert_image": {"template"},
    "kw_assert_image_not_exists": {"template"},
    "scroll_to_height": set(),
    "execute_script": {"script"},
    "press_key": {"key"},
    "press_type": {"keys"},
    "save_page_img": {"name"},
    "mouse_click": {"x", "y"},
    "move_mouse": {"x", "y"},
    "mouse_wheel": set(),
    "wait_for_element": {"locator"},
    "wait_for_element_hidden": {"locator"},
    "wait_for_element_text_change": {"locator"},
    "wait_for_element_text_stable": {"locator"},
    "wait_for_clickable": {"locator"},
    "click_if_exists": {"locator"},
    "fill_if_exists": {"locator", "value"},
    "click_if_visible": {"locator"},
    "fill_if_visible": {"locator", "value"},
    "wait_for_url_contains": {"url"},
    "wait_for_response": {"url"},
    "wait_for_download": {},
    "accept_dialog": {},
    "dismiss_dialog": {},
    "scroll_to_element": {"locator"},
    "click_by_text": {"text"},
    "switch_to_latest_page": set(),
    "kw_assert_page_title": {"title"},
    "kw_assert_page_url": {"url"},
    "kw_assert_value": {"locator", "value"},
    "kw_assert_element_text": {"locator", "text"},
    "kw_assert_element_text_contains": {"locator", "text"},
    "kw_assert_text_contains": {"text"},
    "kw_assert_text_not_contains": {"text"},
    "kw_assert_element_count": {"locator", "count"},
    "kw_assert_text_length": set(),
    "kw_assert_attribute": {"locator", "attr_name", "value"},
    "kw_assert_attribute_exists": {"locator", "attr_name"},
    "kw_assert_attribute_not_exists": {"locator", "attr_name"},
    "kw_assert_visible": {"locator"},
    "kw_assert_hidden": {"locator"},
    "kw_assert_not_exist": {"locator"},
    "kw_assert_not_visible": {"locator"},
    "kw_assert_enabled": {"locator"},
    "kw_assert_disabled": {"locator"},
    "kw_assert_checked": {"locator"},
    "kw_assert_empty": {"locator"},
    "kw_assert_editable": {"locator"},
    "kw_assert_focused": {"locator"},
    "extract_text": {"locator", "var_name"},
    "extract_attribute": {"locator", "attr_name", "var_name"},
    "extract_input_value": {"locator", "var_name"},
    "extract_page_url": {"var_name"},
    "extract_response_field": {"field", "var_name"},
    "smart_step": {"intent"},
    # smart_* / KW-1b 必填须与 frontend stepHelper.validateStep 同步
    "smart_click": {"target", "intent"},
    "smart_fill": {"target", "intent", "value"},
    "frame_fill_value": {"frame", "locator"},
    "frame_click_element": {"frame", "locator"},
    "frame_hover": {"frame", "locator"},
    "frame_focus_element": {"frame", "locator"},
    "frame_select_option": {"frame", "locator", "value"},
    "frame_type_value": {"frame", "locator"},
    "frame_long_click_element": {"frame", "locator"},
    "frame_drag_and_drop": {"frame", "start_selector", "end_selector"},
}

UI_DEFAULT_PARAMS = {
    "open_browser": {"browser_type": "chromium"},
    "click_ele": {
        "index": 1, "force": False, "timeout": 20000,
        "wait_download": False, "download_timeout": 60000,
        "accept_dialog": False, "dismiss_dialog": False, "dialog_timeout": 10000,
    },
    "double_click_ele": {"index": 1, "force": False, "timeout": 20000},
    "fill_value": {"timeout": 20000},
    "type_value": {"timeout": 20000},
    "hover": {"timeout": 20000},
    "focus_element": {"timeout": 20000},
    "select_option": {"timeout": 20000},
    "clear_value": {"timeout": 20000},
    "set_checked": {"timeout": 20000},
    "upload_file": {"timeout": 20000},
    "click_by_image": {"threshold": 0.8, "timeout": 20000},
    "fill_by_image": {"threshold": 0.8, "timeout": 20000, "clear_first": True},
    "wait_for_image": {"threshold": 0.8, "timeout": 20000},
    "kw_assert_image": {"threshold": 0.8, "timeout": 20000},
    "kw_assert_image_not_exists": {"threshold": 0.8, "timeout": 20000},
    "long_click_element": {"delay": 0.1},
    "drag_and_drop": {"timeout": 20000},
    "wait_for_element": {"timeout": 20000},
    "wait_for_element_hidden": {"timeout": 20000, "index": 1},
    "wait_for_element_text_change": {"timeout": 20000, "index": 1},
    "wait_for_element_text_stable": {"timeout": 20000, "stable_ms": 500, "index": 1},
    "wait_for_clickable": {"timeout": 20000, "index": 1},
    "click_if_exists": {"index": 1, "force": False, "timeout": 5000},
    "fill_if_exists": {"index": 1, "timeout": 5000},
    "click_if_visible": {"index": 1, "force": False, "timeout": 5000},
    "fill_if_visible": {"index": 1, "timeout": 5000},
    "wait_for_url_contains": {"timeout": 20000, "use_regex": False},
    "wait_for_response": {"timeout": 30000},
    "wait_for_download": {},
    "accept_dialog": {},
    "dismiss_dialog": {},
    "scroll_to_height": {"position": "height", "height": 0},
    "scroll_to_element": {"timeout": 20000, "index": 1},
    "click_by_text": {
        "index": 1, "exact": False, "force": False, "timeout": 20000,
        "wait_download": False, "download_timeout": 60000,
        "accept_dialog": False, "dismiss_dialog": False, "dialog_timeout": 10000,
    },
    "wait_for_time": {"timeout": 2000},
    "set_default_timeout": {"timeout": 20000},
    "open_url": {"wait_until": "domcontentloaded", "timeout": 30000},
    "go_back": {"timeout": 30000},
    "refresh": {"wait_until": "domcontentloaded", "timeout": 30000},
    "save_page_img": {"name": "screenshot"},
    "mouse_click": {"button": "left", "count": 1},
    "mouse_down": {"button": "left"},
    "mouse_up": {"button": "left"},
    "kw_assert_visible": {"index": 1},
    "kw_assert_hidden": {"index": 1},
    "kw_assert_not_visible": {"index": 1},
    "kw_assert_enabled": {"index": 1},
    "kw_assert_disabled": {"index": 1},
    "kw_assert_checked": {"index": 1},
    "kw_assert_empty": {"index": 1},
    "kw_assert_editable": {"index": 1},
    "kw_assert_focused": {"index": 1},
    "kw_assert_element_text": {"match_mode": "exact"},
    "kw_assert_element_count": {"operator": "eq"},
    "kw_assert_text_length": {"operator": "eq"},
    "extract_text": {"index": 1, "timeout": 20000},
    "extract_attribute": {"index": 1, "timeout": 20000},
    "extract_input_value": {"index": 1, "timeout": 20000},
    "extract_page_url": {"var_name": ""},
    "smart_step": {"intent": ""},
    "smart_click": {
        "allow_ai": False,
        "min_score": 70,
        "min_margin": 15,
        "timeout": 20000,
        "risk_level": "normal",
    },
    "smart_fill": {
        "allow_ai": False,
        "min_score": 70,
        "min_margin": 15,
        "timeout": 20000,
        "risk_level": "normal",
    },
    "frame_fill_value": {"timeout": 20000},
    "frame_click_element": {"index": 1, "button": "left", "force": False, "timeout": 20000},
    "frame_hover": {"timeout": 20000},
    "frame_focus_element": {"timeout": 20000},
    "frame_select_option": {"timeout": 20000},
    "frame_type_value": {"timeout": 20000},
    "frame_long_click_element": {"delay": 0.1},
    "frame_drag_and_drop": {"timeout": 20000},
}

METHOD_TO_KEYWORD = {
    "open_browser": "打开浏览器",
    "open_url": "访问页面url",
    "refresh": "刷新页面",
    "go_back": "页面后退",
    "scroll_to_height": "滚动到指定高度位置",
    "execute_script": "执行JavaScript脚本",
    "save_page_img": "页面截图",
    "open_new_page": "新建窗口页面",
    "switch_to_page": "切换页面",
    "close_page": "关闭页面",
    "reset_browser_context": "清空Cookie",
    "close": "关闭浏览器",
    "fill_value": "元素输入",
    "click_ele": "点击元素",
    "double_click_ele": "双击元素",
    "clear_value": "清空输入框内容",
    "set_checked": "选中复选框",
    "hover": "鼠标悬停到元素上方",
    "focus_element": "聚焦元素",
    "select_option": "选择下拉框的值",
    "type_value": "键盘输入值",
    "drag_and_drop": "拖拽元素",
    "long_click_element": "长按元素",
    "upload_file": "input文件上传",
    "mouse_click": "鼠标点击",
    "move_mouse": "鼠标移动",
    "mouse_down": "鼠标按下",
    "mouse_up": "鼠标抬起",
    "mouse_wheel": "鼠标滚动",
    "press_key": "键盘按键",
    "press_type": "键盘输入文本",
    "frame_fill_value": "iframe内元素输入",
    "frame_click_element": "iframe内元素点击",
    "frame_hover": "iframe内元素悬停",
    "frame_focus_element": "iframe内元素聚焦",
    "frame_select_option": "iframe内下拉框选择",
    "frame_type_value": "iframe内元素键盘输入",
    "frame_long_click_element": "iframe内元素长按",
    "frame_drag_and_drop": "iframe内元素拖拽",
    "set_default_timeout": "默认等待时间",
    "wait_for_time": "强制等待时间",
    "wait_for_load": "等待页面加载完成",
    "wait_for_network": "等待网络请求完成",
    "wait_for_element": "等待元素可见",
    "wait_for_element_hidden": "等待元素消失",
    "wait_for_element_text_change": "等待元素文本变化",
    "wait_for_element_text_stable": "等待元素文本稳定",
    "wait_for_clickable": "等待元素可点击",
    "click_if_exists": "若存在则点击",
    "fill_if_exists": "若存在则输入",
    "click_if_visible": "若可见则点击",
    "fill_if_visible": "若可见则输入",
    "wait_for_url_contains": "等待URL包含",
    "wait_for_response": "等待接口响应",
    "wait_for_download": "等待下载完成",
    "accept_dialog": "接受弹窗",
    "dismiss_dialog": "取消弹窗",
    "scroll_to_element": "滚动到元素",
    "click_by_text": "按文本点击元素",
    "switch_to_latest_page": "切换到最新页面",
    "kw_assert_page_title": "断言页面标题",
    "kw_assert_page_url": "断言页面url地址",
    "kw_assert_value": "断言元素value属性",
    "kw_assert_element_text": "断言元素文本值",
    "kw_assert_element_text_contains": "断言元素文本包含",
    "kw_assert_text_contains": "断言文本包含",
    "kw_assert_text_not_contains": "断言文本不包含",
    "kw_assert_element_count": "断言元素数量",
    "kw_assert_text_length": "断言文本长度",
    "kw_assert_attribute": "断言元素属性值",
    "kw_assert_attribute_exists": "断言元素属性存在",
    "kw_assert_attribute_not_exists": "断言元素属性不存在",
    "kw_assert_visible": "断言元素可见",
    "kw_assert_hidden": "断言元素隐藏",
    "kw_assert_not_exist": "断言元素不存在",
    "kw_assert_not_visible": "断言元素不可见",
    "kw_assert_enabled": "断言元素可用",
    "kw_assert_disabled": "断言元素被禁用",
    "kw_assert_checked": "断言元素被选中",
    "kw_assert_empty": "断言元素为空",
    "kw_assert_editable": "断言元素可编辑",
    "kw_assert_focused": "断言元素获取焦点",
    "kw_db_assert": "数据库断言",
    "extract_text": "提取元素文本",
    "extract_attribute": "提取元素属性",
    "extract_input_value": "提取控件值",
    "extract_page_url": "提取当前页面url",
    "extract_response_field": "提取接口响应字段",
    "smart_step": "智能步骤",
    "smart_click": "智能点击",
    "smart_fill": "智能输入",
    "condition_branch": "条件分支",
    "click_by_image": "图像模板点击",
    "fill_by_image": "图像模板输入",
    "wait_for_image": "等待图像出现",
    "kw_assert_image": "断言图像存在",
    "kw_assert_image_not_exists": "断言图像不存在",
}


def validate_smart_step_params(method: str, params=None):
    """SMART-1：校验 expected_after 类型与危险动作安全字段。返回错误文案列表。"""
    if method not in ("smart_click", "smart_fill"):
        return []
    params = params if isinstance(params, dict) else {}
    errors = []
    ea = params.get("expected_after")
    if ea is not None:
        if not isinstance(ea, dict):
            errors.append("expected_after 必须是对象")
        else:
            ea_type = str(ea.get("type") or "").strip()
            # 空对象 / 无 type = 未配置后置（允许）；仅当显式填了 type 才校验白名单
            if ea_type and ea_type not in SMART_EXPECTED_AFTER_TYPES:
                errors.append(
                    f"expected_after.type 不支持: {ea_type}，"
                    f"允许: {', '.join(sorted(SMART_EXPECTED_AFTER_TYPES))}"
                )
            if ea_type in ("locator_visible", "locator_hidden"):
                if not str(ea.get("locator") or "").strip():
                    errors.append(f"expected_after.{ea_type} 必须填写 locator")
            if ea_type == "text_visible" and not str(ea.get("text") or "").strip():
                errors.append("expected_after.text_visible 必须填写 text")
            if ea_type == "url_contains" and not str(
                ea.get("text") or ea.get("url") or ""
            ).strip():
                errors.append("expected_after.url_contains 必须填写 URL 片段")
            try:
                to = ea.get("timeout")
                if to is not None and float(to) < 0:
                    errors.append("expected_after.timeout 不能为负数")
            except (TypeError, ValueError):
                errors.append("expected_after.timeout 必须是数字")

    # 危险词：保存侧与 Runner 一致，缺 region/后置则报错
    # 不含「确定/确认」——普通确认弹层不强制；删除确认靠 target 含「删除」命中
    # 须与 runner/tools/smart_action.py、frontend stepHelper.validateSmartStepParams 同步
    target = str(params.get("target") or "")
    risk = str(params.get("risk_level") or "").strip().lower()
    destructive_words = (
        "删除", "移除", "提交", "发布", "支付",
        "delete", "remove", "submit", "publish", "pay",
    )
    if risk in ("submit", "destructive") or any(w in target for w in destructive_words):
        if not str(params.get("region") or "").strip():
            errors.append("危险动作（删除/提交等）必须填写 region")
        if not isinstance(ea, dict) or not str((ea or {}).get("type") or "").strip():
            errors.append("危险动作必须填写 expected_after")
    return errors
