/** 内置文档 id（与 backend app/core/docs_catalog.py BUILTIN_DOC_ENTRIES 保持一致） */
export const BUILTIN_DOC_IDS = new Set([
  'home',
  'quick-start',
  'highlights',
  'release-notes',
  'project-setup',
  'test-catalog',
  'ui-automation',
  'app-automation',
  'api-automation',
  'data-factory',
  'api-auth',
  'perf-testing',
  'ai-testing',
  'browser-lab',
  'platform-assistant',
  'mcp-server',
  'runner-client',
  'runner-install-guide',
  'runner-packaging',
  'runner-troubleshooting',
  'runner-linux-server',
  'docker-deploy',
  'system-admin',
])
