"""
UI 自动化步骤关键字目录（与 frontend ActionGroup.js、Runner KeywordRegistry 对齐）
"""

UI_VALID_METHODS = {
    "open_browser", "open_url", "refresh", "go_back", "scroll_to_height", "execute_script",
    "save_page_img", "open_new_page", "switch_to_page", "close_page",
    "reset_browser_context", "close",
    "fill_value", "click_ele", "double_click_ele", "clear_value", "set_checked",
    "hover", "focus_element", "select_option", "type_value", "drag_and_drop",
    "long_click_element", "upload_file",
    "mouse_click", "move_mouse", "mouse_down", "mouse_up", "mouse_wheel",
    "press_key", "press_type",
    "frame_fill_value", "frame_click_element", "frame_hover", "frame_focus_element",
    "frame_select_option", "frame_type_value", "frame_long_click_element",
    "frame_drag_and_drop",
    "set_default_timeout", "wait_for_time", "wait_for_load", "wait_for_network",
    "wait_for_element",
    "kw_assert_page_title", "kw_assert_page_url", "kw_assert_value",
    "kw_assert_element_text", "kw_assert_element_text_contains", "kw_assert_text_contains",
    "kw_assert_attribute", "kw_assert_visible",
    "kw_assert_hidden", "kw_assert_not_exist", "kw_assert_not_visible",
    "kw_assert_enabled", "kw_assert_disabled",
    "kw_assert_checked", "kw_assert_empty", "kw_assert_editable", "kw_assert_focused",
    "kw_db_assert",
    "extract_text", "extract_attribute",
    "condition_branch",
}

UI_REQUIRED_PARAMS = {
    "open_url": {"url"},
    "fill_value": {"locator"},
    "click_ele": {"locator"},
    "double_click_ele": {"locator"},
    "clear_value": {"locator"},
    "set_checked": {"locator"},
    "hover": {"locator"},
    "focus_element": {"locator"},
    "select_option": {"locator", "value"},
    "type_value": {"locator"},
    "drag_and_drop": {"start_selector", "end_selector"},
    "long_click_element": {"locator"},
    "upload_file": {"locator"},
    "scroll_to_height": {"height"},
    "execute_script": {"script"},
    "press_key": {"key"},
    "press_type": {"keys"},
    "save_page_img": {"name"},
    "mouse_click": {"x", "y"},
    "move_mouse": {"x", "y"},
    "mouse_wheel": {"x", "y"},
    "wait_for_element": {"locator"},
    "kw_assert_page_title": {"title"},
    "kw_assert_page_url": {"url"},
    "kw_assert_value": {"locator", "value"},
    "kw_assert_element_text": {"locator", "text"},
    "kw_assert_element_text_contains": {"locator", "text"},
    "kw_assert_text_contains": {"text"},
    "kw_assert_attribute": {"locator", "attr_name", "value"},
    "kw_assert_visible": {"locator"},
    "kw_assert_hidden": {"locator"},
    "kw_assert_not_exist": {"locator"},
    "kw_assert_not_visible": {"locator"},
    "kw_assert_enabled": {"locator"},
    "kw_assert_disabled": {"locator"},
    "kw_assert_checked": {"locator"},
    "kw_assert_empty": {"locator"},
    "kw_assert_editable": {"locator"},
    "kw_assert_focused": {"locator"},
    "extract_text": {"locator", "var_name"},
    "extract_attribute": {"locator", "attr_name", "var_name"},
    "frame_fill_value": {"frame", "locator"},
    "frame_click_element": {"frame", "locator"},
    "frame_hover": {"frame", "locator"},
    "frame_focus_element": {"frame", "locator"},
    "frame_select_option": {"frame", "locator", "value"},
    "frame_type_value": {"frame", "locator"},
    "frame_long_click_element": {"frame", "locator"},
    "frame_drag_and_drop": {"frame", "start_selector", "end_selector"},
}

UI_DEFAULT_PARAMS = {
    "open_browser": {"browser_type": "chromium"},
    "click_ele": {"index": 1, "force": False, "timeout": 20000},
    "double_click_ele": {"index": 1, "force": False, "timeout": 20000},
    "fill_value": {"timeout": 20000},
    "type_value": {"timeout": 20000},
    "hover": {"timeout": 20000},
    "focus_element": {"timeout": 20000},
    "select_option": {"timeout": 20000},
    "clear_value": {"timeout": 20000},
    "set_checked": {"timeout": 20000},
    "upload_file": {"timeout": 20000},
    "long_click_element": {"delay": 0.1},
    "drag_and_drop": {"timeout": 20000},
    "wait_for_element": {"timeout": 20000},
    "wait_for_time": {"timeout": 2000},
    "set_default_timeout": {"timeout": 20000},
    "open_url": {"wait_until": "load", "timeout": 30000},
    "save_page_img": {"name": "screenshot"},
    "mouse_click": {"button": "left", "count": 1},
    "mouse_down": {"button": "left"},
    "mouse_up": {"button": "left"},
    "kw_assert_visible": {"index": 1},
    "kw_assert_hidden": {"index": 1},
    "kw_assert_not_visible": {"index": 1},
    "kw_assert_enabled": {"index": 1},
    "kw_assert_disabled": {"index": 1},
    "kw_assert_checked": {"index": 1},
    "kw_assert_empty": {"index": 1},
    "kw_assert_editable": {"index": 1},
    "kw_assert_focused": {"index": 1},
    "kw_assert_element_text": {"match_mode": "exact"},
    "extract_text": {"index": 1, "timeout": 20000},
    "extract_attribute": {"index": 1, "timeout": 20000},
    "frame_fill_value": {"timeout": 20000},
    "frame_click_element": {"index": 1, "button": "left", "force": False, "timeout": 20000},
    "frame_hover": {"timeout": 20000},
    "frame_focus_element": {"timeout": 20000},
    "frame_select_option": {"timeout": 20000},
    "frame_type_value": {"timeout": 20000},
    "frame_long_click_element": {"delay": 0.1},
    "frame_drag_and_drop": {"timeout": 20000},
}

METHOD_TO_KEYWORD = {
    "open_browser": "打开浏览器",
    "open_url": "访问页面url",
    "refresh": "刷新页面",
    "go_back": "页面后退",
    "scroll_to_height": "滚动到指定高度位置",
    "execute_script": "执行JavaScript脚本",
    "save_page_img": "页面截图",
    "open_new_page": "新建窗口页面",
    "switch_to_page": "切换页面",
    "close_page": "关闭页面",
    "reset_browser_context": "清空Cookie",
    "close": "关闭浏览器",
    "fill_value": "元素输入",
    "click_ele": "点击元素",
    "double_click_ele": "双击元素",
    "clear_value": "清空输入框内容",
    "set_checked": "选中复选框",
    "hover": "鼠标悬停到元素上方",
    "focus_element": "聚焦元素",
    "select_option": "选择下拉框的值",
    "type_value": "键盘输入值",
    "drag_and_drop": "拖拽元素",
    "long_click_element": "长按元素",
    "upload_file": "input文件上传",
    "mouse_click": "鼠标点击",
    "move_mouse": "鼠标移动",
    "mouse_down": "鼠标按下",
    "mouse_up": "鼠标抬起",
    "mouse_wheel": "鼠标滚动",
    "press_key": "键盘按键",
    "press_type": "键盘输入文本",
    "frame_fill_value": "iframe内元素输入",
    "frame_click_element": "iframe内元素点击",
    "frame_hover": "iframe内元素悬停",
    "frame_focus_element": "iframe内元素聚焦",
    "frame_select_option": "iframe内下拉框选择",
    "frame_type_value": "iframe内元素键盘输入",
    "frame_long_click_element": "iframe内元素长按",
    "frame_drag_and_drop": "iframe内元素拖拽",
    "set_default_timeout": "默认等待时间",
    "wait_for_time": "强制等待时间",
    "wait_for_load": "等待页面加载完成",
    "wait_for_network": "等待网络请求完成",
    "wait_for_element": "等待元素可见",
    "kw_assert_page_title": "断言页面标题",
    "kw_assert_page_url": "断言页面url地址",
    "kw_assert_value": "断言元素value属性",
    "kw_assert_element_text": "断言元素文本值",
    "kw_assert_element_text_contains": "断言元素文本包含",
    "kw_assert_text_contains": "断言文本包含",
    "kw_assert_attribute": "断言元素属性值",
    "kw_assert_visible": "断言元素可见",
    "kw_assert_hidden": "断言元素隐藏",
    "kw_assert_not_exist": "断言元素不存在",
    "kw_assert_not_visible": "断言元素不可见",
    "kw_assert_enabled": "断言元素可用",
    "kw_assert_disabled": "断言元素被禁用",
    "kw_assert_checked": "断言元素被选中",
    "kw_assert_empty": "断言元素为空",
    "kw_assert_editable": "断言元素可编辑",
    "kw_assert_focused": "断言元素获取焦点",
    "kw_db_assert": "数据库断言",
    "extract_text": "提取元素文本",
    "extract_attribute": "提取元素属性",
    "condition_branch": "条件分支",
}
